#!/bin/bash
echo ""
echo "╔══════════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                              ║"
echo "║              🤖 AI Customer Support - Setup Assistant 🤖                     ║"
echo "║                                                                              ║"
echo "╚══════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "This will help you set up your AI customer support in 3 minutes!"
echo ""
echo "📋 Step 1: Get Your Free API Key"
echo "   → Open: https://makersuite.google.com/app/apikey"
echo "   → Sign in with Google"
echo "   → Click 'Create API Key'"
echo "   → Copy the key"
echo ""
read -p "Press Enter when you have your API key ready..."
echo ""
echo "📝 Step 2: Enter Your API Key"
read -p "Paste your Gemini API key here: " API_KEY
echo ""
if [ -z "$API_KEY" ]; then
    echo "❌ No API key provided. Exiting."
    exit 1
fi
echo "VITE_GEMINI_API_KEY=$API_KEY" > .env
echo "✅ API key saved to .env file"
echo ""
echo "🔄 Step 3: Restart Development Server"
echo ""
echo "Run these commands:"
echo "   npm run dev"
echo ""
echo "Then look for the blue chat button in the bottom-right corner!"
echo ""
echo "╔══════════════════════════════════════════════════════════════════════════════╗"
echo "║                           ✅ Setup Complete! ✅                               ║"
echo "╚══════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📚 Documentation:"
echo "   • Quick Start: cat AI_SUPPORT_QUICKSTART.md"
echo "   • Full Docs:   cat CUSTOMER_SUPPORT_README.md"
echo "   • Checklist:   cat SETUP_CHECKLIST.md"
echo ""
